# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MY SIRR
       Minimalist agro-hYdrologicalmodel for Sustainable IRRigation management- soil moisture and crop dynamics
 MY SIRR
                              -------------------
        versione             : v.3.0
        author	             : Raffaele Albano
        contact              : http://www2.unibas.it/raffaelealbano/?page_id=115
 ***************************************************************************/
/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Wed Oct 19 14:28:57 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
import images_qr
import sys

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setWindowModality(QtCore.Qt.NonModal)
        mainWindow.resize(1013, 517)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(1013, 517))
        mainWindow.setMaximumSize(QtCore.QSize(1013, 517))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icone/main.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.goText = QtGui.QTextEdit(self.centralwidget)
        self.goText.setEnabled(True)
        self.goText.setGeometry(QtCore.QRect(110, 430, 901, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goText.sizePolicy().hasHeightForWidth())
        self.goText.setSizePolicy(sizePolicy)
        self.goText.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.goText.setObjectName("goText")
        self.goButton = QtGui.QPushButton(self.centralwidget)
        self.goButton.setGeometry(QtCore.QRect(10, 430, 81, 51))
        self.goButton.setObjectName("goButton")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 741, 401))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setObjectName("groupBox")
        self.textEditClimate = QtGui.QTextEdit(self.groupBox)
        self.textEditClimate.setGeometry(QtCore.QRect(240, 40, 441, 31))
        self.textEditClimate.setObjectName("textEditClimate")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(140, 20, 90, 70))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icone/climate.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(140, 90, 90, 70))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icone/soil.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(140, 160, 90, 70))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icone/crop.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(140, 230, 90, 70))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icone/management.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.textEditSoil = QtGui.QTextEdit(self.groupBox)
        self.textEditSoil.setGeometry(QtCore.QRect(240, 110, 441, 31))
        self.textEditSoil.setObjectName("textEditSoil")
        self.textEditCrop = QtGui.QTextEdit(self.groupBox)
        self.textEditCrop.setGeometry(QtCore.QRect(240, 180, 441, 31))
        self.textEditCrop.setObjectName("textEditCrop")
        self.textEditMan = QtGui.QTextEdit(self.groupBox)
        self.textEditMan.setGeometry(QtCore.QRect(240, 250, 441, 31))
        self.textEditMan.setObjectName("textEditMan")
        self.toolButtonClimate = QtGui.QToolButton(self.groupBox)
        self.toolButtonClimate.setGeometry(QtCore.QRect(690, 40, 41, 31))
        self.toolButtonClimate.setAutoFillBackground(False)
        self.toolButtonClimate.setIconSize(QtCore.QSize(30, 30))
        self.toolButtonClimate.setObjectName("toolButtonClimate")
        self.toolButtonSoil = QtGui.QToolButton(self.groupBox)
        self.toolButtonSoil.setGeometry(QtCore.QRect(690, 110, 41, 31))
        self.toolButtonSoil.setIconSize(QtCore.QSize(30, 30))
        self.toolButtonSoil.setObjectName("toolButtonSoil")
        self.toolButtonCrop = QtGui.QToolButton(self.groupBox)
        self.toolButtonCrop.setGeometry(QtCore.QRect(690, 180, 41, 31))
        self.toolButtonCrop.setIconSize(QtCore.QSize(30, 30))
        self.toolButtonCrop.setObjectName("toolButtonCrop")
        self.toolButtonMan = QtGui.QToolButton(self.groupBox)
        self.toolButtonMan.setGeometry(QtCore.QRect(690, 250, 41, 31))
        self.toolButtonMan.setIconSize(QtCore.QSize(30, 30))
        self.toolButtonMan.setObjectName("toolButtonMan")
        self.textEditOutput = QtGui.QTextEdit(self.groupBox)
        self.textEditOutput.setEnabled(True)
        self.textEditOutput.setGeometry(QtCore.QRect(240, 320, 441, 31))
        self.textEditOutput.setObjectName("textEditOutput")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(150, 300, 80, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.toolButtonOutput = QtGui.QToolButton(self.groupBox)
        self.toolButtonOutput.setEnabled(True)
        self.toolButtonOutput.setGeometry(QtCore.QRect(690, 320, 41, 31))
        self.toolButtonOutput.setObjectName("toolButtonOutput")
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(40, 50, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(40, 120, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(40, 190, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(10, 260, 111, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(780, 20, 231, 401))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 46, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 170, 91, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 220, 46, 13))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 130, 71, 16))
        self.label_10.setObjectName("label_10")
        self.spinBoxCell = QtGui.QSpinBox(self.groupBox_2)
        self.spinBoxCell.setGeometry(QtCore.QRect(110, 220, 42, 22))
        self.spinBoxCell.setProperty("value", 1)
        self.spinBoxCell.setObjectName("spinBoxCell")
        self.doubleSpinBoxSstart = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxSstart.setGeometry(QtCore.QRect(110, 170, 62, 22))
        self.doubleSpinBoxSstart.setProperty("value", 0.2)
        self.doubleSpinBoxSstart.setObjectName("doubleSpinBoxSstart")
        self.checkBoxRain = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxRain.setGeometry(QtCore.QRect(110, 130, 70, 17))
        self.checkBoxRain.setText("")
        self.checkBoxRain.setObjectName("checkBoxRain")
        self.comboBoxET = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxET.setGeometry(QtCore.QRect(110, 50, 111, 22))
        self.comboBoxET.setObjectName("comboBoxET")
        self.comboBoxET.addItem("")
        self.comboBoxET.addItem("")
        self.comboBoxET.addItem("")
        self.comboBoxVico = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxVico.setGeometry(QtCore.QRect(110, 90, 111, 22))
        self.comboBoxVico.setObjectName("comboBoxVico")
        self.comboBoxVico.addItem("")
        self.comboBoxVico.addItem("")
        self.checkBoxOptimization = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxOptimization.setGeometry(QtCore.QRect(110, 260, 81, 17))
        self.checkBoxOptimization.setText("")
        self.checkBoxOptimization.setObjectName("checkBoxOptimization")
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(10, 280, 46, 13))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(10, 260, 81, 16))
        self.label_16.setObjectName("label_16")
        mainWindow.setCentralWidget(self.centralwidget)
        if sys.platform == 'darwin':
            self.menuBar = QtGui.QMenuBar()
        else:
            self.menuBar = QtGui.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1013, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.action_RecentProject = QtGui.QMenu(self.menuFile)
        self.action_RecentProject.setObjectName("action_RecentProject")
        mainWindow.setMenuBar(self.menuBar)
        self.actionOpen_Project = QtGui.QAction(mainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionProject_1 = QtGui.QAction(mainWindow)
        self.actionProject_1.setObjectName("actionProject_1")
        self.actionSave_As = QtGui.QAction(mainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionSave = QtGui.QAction(mainWindow)
        self.actionSave.setObjectName("actionSave")
        self.action_RecentProject.addSeparator()
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_RecentProject.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "mysirrGUI", None, QtGui.QApplication.UnicodeUTF8))
        self.goButton.setText(QtGui.QApplication.translate("mainWindow", "Run simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("mainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonClimate.setText(QtGui.QApplication.translate("mainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonSoil.setText(QtGui.QApplication.translate("mainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonCrop.setText(QtGui.QApplication.translate("mainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonMan.setText(QtGui.QApplication.translate("mainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("mainWindow", "OUTPUT", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonOutput.setText(QtGui.QApplication.translate("mainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("mainWindow", "CLIMATE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("mainWindow", "SOIL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("mainWindow", "CROP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("mainWindow", "MANAGEMENT", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("mainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("mainWindow", "ET", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("mainWindow", "YELD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("mainWindow", "SOIL MOIST. start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("mainWindow", "Cell ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("mainWindow", "RANDOM RAIN", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxET.setToolTip(QtGui.QApplication.translate("mainWindow", "<html><head/><body><p>ET method</p><p>N = data loaded from file</p><p>BC= Blaney_Criddle</p><p>PM = Penman-Monteith</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxET.setItemText(0, QtGui.QApplication.translate("mainWindow", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxET.setItemText(1, QtGui.QApplication.translate("mainWindow", "BC", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxET.setItemText(2, QtGui.QApplication.translate("mainWindow", "PM", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxVico.setToolTip(QtGui.QApplication.translate("mainWindow", "<html><head/><body><p>Yeld empirical (vico2011) or dichotomic (vico2013) formula</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxVico.setItemText(0, QtGui.QApplication.translate("mainWindow", "EMP", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxVico.setItemText(1, QtGui.QApplication.translate("mainWindow", "DIC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("mainWindow", "OPTIMIZATION", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("mainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.action_RecentProject.setTitle(QtGui.QApplication.translate("mainWindow", "Recent Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Project.setText(QtGui.QApplication.translate("mainWindow", "Open Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProject_1.setText(QtGui.QApplication.translate("mainWindow", "project 1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("mainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("mainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))

